### ISSUE TITLE
Error undefined 'map' from @pinia

### ISSUE THREAD

**Issue by IndeedEvan** [Guiqft/nuxt3-primevue-directus#4]
Hello, here is my error using node 17.0.1, tested on 14.16 too..

Maybe i'm doing something wrong ? Also tried pinia on nuxt-3 (not using this CLI) without success.

` WARN  [SSR] Error transforming virtual:C:/Users/Evan/Desktop/create-nuxt3-directus/x/.nuxt/plugins/server.mjs: Error: Parse failure: Bad character escape sequence (5:74)
Contents of line 5: import plugin_69f1ba1b from 'C:\Users\Evan\Desktop\create-nuxt3-directus\x\node_modules\@pinia\nuxt\dist\plugin.mjs'

√ Vite server built in 2673ms                                                                              19:29:06
√ Nitro built in 187 ms                                                                                    19:29:06
Cannot read properties of undefined (reading 'map')
  at Module.normalizePlugins (file:///C:/Users/Evan/Desktop/create-nuxt3-directus/x/.nuxt/dist/server/server.mjs:177:28)
  at $id_35820998 (file:///C:/Users/Evan/Desktop/create-nuxt3-directus/x/.nuxt/dist/server/server.mjs:28:39)
  at async __instantiateModule__ (file:///C:/Users/Evan/Desktop/create-nuxt3-directus/x/.nuxt/dist/server/server.mjs:1016:3)
Cannot read properties of undefined (reading 'map')
  at Module.normalizePlugins (file:///C:/Users/Evan/Desktop/create-nuxt3-directus/x/.nuxt/dist/server/server.mjs:177:28)
  at $id_35820998 (file:///C:/Users/Evan/Desktop/create-nuxt3-directus/x/.nuxt/dist/server/server.mjs:28:39)
  at async __instantiateModule__ (file:///C:/Users/Evan/Desktop/create-nuxt3-directus/x/.nuxt/dist/server/server.mjs:1016:3)`

Thanks for you work, this boilerplate is going to be very useful to me 👍 💯

**Comment by IndeedEvan** [comment]
Deleted node_modules / yarn.lock, started again with Node 16.11.0 and it's working nice. 

*hide*

**Comment by Guiqft** [comment]
Nice! 🥳
